import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.scss';
import 'the-new-css-reset/css/reset.css';
import { LoadingProvider } from '@/scripts/loading/LoadingContext';

const lato = Lato({ subsets: ['latin'], weight: ['300', '400', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
                                     children
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <LoadingProvider>
      <body className={lato.className}>{children}</body>
    </LoadingProvider>
    </html>
  );
}
